# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for building and running the server
FROM node:22.12-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package files and the lock file
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY src ./src
COPY tsconfig.json ./

# Build the server
RUN npm run build

# Prepare the runtime image
FROM node:22-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/build /app/build
COPY package.json package-lock.json ./

# Install production dependencies
RUN npm ci --only=production

# Copy the .env file to the container
COPY .env ./

# Define the environment variable for the Kagi API key
ENV KAGI_API_KEY=your_api_key_here

# Specify the command to run the MCP server
CMD ["node", "build/index.js"]